'use client';
import {useState} from 'react';
import {Button,Card,QueryBoundary} from '@dbl/ui';
import {useCmd,useOp,errView} from '@/lib/hooks';
import {ErrorNote,StatusChip} from './bits';
import {AreaField,FormGrid,SelectField} from './fields';
export function AccessControl() {
 const members=useOp('listMembers'),roles=useOp('listRoles'),me=useOp('getMe'),directory=useOp('getWorkDirectory');const [id,setId]=useState(''),[count,setCount]=useState(1);
 const options={invalidate:['listMembers','listRoles'] as ('listMembers'|'listRoles')[]},status=useCmd('changeMemberStatus',options),revoke=useCmd('revokeMemberSessions',options),grants=useCmd('replaceMemberGrants',options);const rows=(members.data as any[])??[],m=rows.find(r=>r.id===id),d=directory.data as any;
 const subject=(me.data as any)?.userId;const self=m?.id===(me.data as any)?.membershipId;void subject;
 return <Card title="Membership access control"><QueryBoundary status={members.status} error={errView(members.error)}><SelectField label="Membership to manage" aria-label="Membership to manage" value={id} onChange={e=>setId(e.target.value)}><option value="">Select…</option>{rows.map(m=><option key={m.id} value={m.id}>{m.display_name??m.subject} · {m.workspace} · {m.status}</option>)}</SelectField>{m&&<div className="mt-4 grid gap-5"><p className="text-sm">Current status <StatusChip s={m.status}/> · version {m.version}</p><form className="grid gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),action=((e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement).value,reason=String(f.get('reason'));if(action==='sessions')revoke.mutate({params:{id},ifMatch:m.version,body:{reason}});else status.mutate({params:{id},ifMatch:m.version,body:{status:action as any,reason}});}}><AreaField label="Access change reason" name="reason" required minLength={10}/><div className="flex flex-wrap gap-2"><Button type="submit" value="sessions" disabled={revoke.isPending}>Revoke existing sessions</Button>{m.status==='active'?<><Button type="submit" value="suspended" disabled={self||status.isPending}>Suspend membership</Button><Button type="submit" value="revoked" disabled={self||status.isPending}>Revoke membership</Button></>:<Button type="submit" value="active" disabled={self||status.isPending}>Reactivate membership</Button>}</div><p className="text-xs text-steel">Session revocation invalidates previously issued access tokens for this tenant. Reactivation requires a fresh sign-in. OIDC sessions at the identity provider are managed there.</p><ErrorNote e={status.error}/><ErrorNote e={revoke.error}/>{(status.isSuccess||revoke.isSuccess)&&<p role="status">Access change recorded.</p>}</form>
 <form className="grid gap-3 border-t border-line pt-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);grants.mutate({params:{id},ifMatch:m.version,body:{reason:String(f.get('reason')),grants:Array.from({length:count},(_,i)=>({role:String(f.get(`role_${i}`)),legalEntityId:String(f.get(`entity_${i}`)||'')||null,branchId:String(f.get(`branch_${i}`)||'')||null}))}});}}><h3 className="font-semibold">Replace role grants</h3><p className="text-xs text-steel">This replaces all current grants. Entity-wide and branch-specific grants are distinct. External memberships must use their matching portal role.</p>{Array.from({length:count},(_,i)=><fieldset key={i} className="grid gap-3 rounded-sm border border-line p-3"><legend>Grant {i+1}</legend><SelectField label={`Grant ${i+1} role`} aria-label={`Grant ${i+1} role`} name={`role_${i}`} required><option value="">Select…</option>{((roles.data as any[])??[]).map(r=><option key={r.key} value={r.key}>{r.name}</option>)}</SelectField><FormGrid><SelectField label={`Grant ${i+1} legal entity`} aria-label={`Grant ${i+1} legal entity`} name={`entity_${i}`}><option value="">All entities</option>{d?.entities?.map((e:any)=><option key={e.id} value={e.id}>{e.name}</option>)}</SelectField><SelectField label={`Grant ${i+1} branch`} aria-label={`Grant ${i+1} branch`} name={`branch_${i}`}><option value="">All branches in scope</option>{d?.branches?.map((b:any)=><option key={b.id} value={b.id}>{b.name}</option>)}</SelectField></FormGrid></fieldset>)}<div className="flex gap-2"><Button type="button" variant="ghost" disabled={count>=30} onClick={()=>setCount(n=>n+1)}>Add grant</Button><Button type="button" variant="ghost" disabled={count<=1} onClick={()=>setCount(n=>n-1)}>Remove last grant</Button></div><AreaField label="Grant replacement reason" name="reason" required minLength={10}/><Button type="submit" disabled={self||grants.isPending}>Replace all grants</Button><ErrorNote e={grants.error}/>{grants.isSuccess&&<p role="status">Role grants replaced and existing access tokens revoked.</p>}</form></div>}</QueryBoundary></Card>;
}
export function OperationsHealth() {
 const q=useOp('getOperationsHealth'),d=q.data as any;const labels:Record<string,string>={pending_events:'Pending outbox events',oldest_event_seconds:'Oldest event age (seconds)',failed_workflows:'Failed workflows',failed_messages:'Failed outbound messages',pending_scans:'Documents awaiting scan',active_members:'Active members'};
 return <Card title="Tenant operations health"><QueryBoundary status={q.status} error={errView(q.error)}>{d&&<><dl className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(labels).map(([key,label])=><div key={key} className="rounded-sm border border-line p-3"><dt className="text-xs text-steel">{label}</dt><dd className="mt-1 font-mono text-2xl">{d[key]}</dd></div>)}</dl><p className="mt-3 text-xs text-steel">Observed {new Date(d.observed_at).toLocaleString()}. These are tenant queue metrics, not proof of provider delivery or overall infrastructure health.</p><Button variant="ghost" onClick={()=>q.refetch()}>Refresh operations health</Button></>}</QueryBoundary></Card>;
}
