'use client';
import {useState} from 'react';
import {Button,Card,QueryBoundary} from '@dbl/ui';
import {useCmd,useOp,errView} from '@/lib/hooks';
import {ErrorNote,StatusChip} from './bits';
import {AreaField,SelectField} from './fields';
export function AccountingPeriods(){
 const q=useOp('listAccountingPeriods'),me=useOp('getMe'),[selected,setSelected]=useState('');const permissions=(me.data as any)?.permissions??[];
 return <><Card title="Accounting periods"><QueryBoundary status={q.status} error={errView(q.error)}><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Legal entity','Period','Status','Version'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{((q.data as any[])??[]).map(p=><tr key={p.id} className="border-t border-line"><td className="p-2">{p.legal_entity}</td><td className="p-2"><button className="underline" onClick={()=>setSelected(p.id)}>{String(p.start_date).slice(0,10)} → {String(p.end_date).slice(0,10)}</button></td><td className="p-2"><StatusChip s={p.status}/></td><td className="p-2">{p.version}</td></tr>)}</tbody></table></div></QueryBoundary></Card>{selected&&<Period key={selected} id={selected} request={permissions.includes('finance.period.request')} decide={permissions.includes('finance.period.decide')} membershipId={(me.data as any)?.membershipId}/>}</>;
}
function Period({id,request,decide,membershipId}:{id:string;request:boolean;decide:boolean;membershipId:string}){
 const q=useOp('getAccountingPeriod',{params:{id}}),r=q.data as any,create=useCmd('requestPeriodChange',{invalidate:['getAccountingPeriod','listAccountingPeriods']});return <QueryBoundary status={q.status} error={errView(q.error)}>{r&&<><Card title="Period reconciliation" actions={<StatusChip s={r.status}/>}><p className="text-sm">{r.trialBalance.journalCount} journals · {r.trialBalance.unpostedInvoices} unposted invoices · {r.trialBalance.invalidJournals} invalid or empty journals</p><p className="mt-2 text-xs text-steel">This is period movement by account and currency. It excludes opening balances, group consolidation, statutory reporting and FX revaluation.</p><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Currency','Account','Debit','Credit','Net movement'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{r.trialBalance.balances.map((b:any)=><tr key={b.currency+b.code} className="border-t border-line"><td className="p-2">{b.currency}</td><td className="p-2">{b.code} · {b.name}</td><td className="p-2 font-mono">{b.debit}</td><td className="p-2 font-mono">{b.credit}</td><td className="p-2 font-mono">{b.balance}</td></tr>)}</tbody></table></div>{request&&<form className="mt-4 grid gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);create.mutate({params:{id},ifMatch:r.version,body:{kind:String(f.get('kind')) as 'close'|'reopen',reason:String(f.get('reason'))}});}}><SelectField label="Period change" aria-label="Period change" name="kind" key={r.status} defaultValue={r.status==='open'?'close':'reopen'}><option value="close">Close reconciled ended period</option><option value="reopen">Reopen for controlled correction</option></SelectField><AreaField label="Period change reason and reconciliation evidence" name="reason" required minLength={10}/><Button type="submit" disabled={create.isPending||r.requests.some((x:any)=>x.status==='pending')}>Request reviewed period change</Button><ErrorNote e={create.error}/></form>}</Card><Card title="Period change history"><ul className="grid gap-4">{r.requests.map((a:any)=><li className="rounded-sm border border-line p-3 text-sm" key={a.id}><div className="flex items-center gap-2"><b>{a.kind}</b><StatusChip s={a.status}/></div><p className="mt-2 whitespace-pre-wrap">{a.reason}</p><p className="mt-1 text-xs text-steel">Requested {new Date(a.requested_at).toLocaleString()} · {a.snapshot.journalCount} reviewed journals</p>{a.decision_note&&<p className="mt-2">Decision: {a.decision_note}</p>}{decide&&a.status==='pending'&&a.requested_by!==membershipId&&<Decision requestId={a.id} version={r.version}/>}</li>)}</ul><p className="mt-3 text-xs text-steel">The requester cannot decide their own change. A changed ledger invalidates approval of the saved snapshot; reject it and prepare a new request.</p></Card></>}</QueryBoundary>;
}
function Decision({requestId,version}:{requestId:string;version:number}){
 const command=useCmd('decidePeriodChange',{invalidate:['getAccountingPeriod','listAccountingPeriods']});return <form className="mt-3 grid gap-3" onSubmit={e=>{e.preventDefault();const approve=((e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement).value==='approve';command.mutate({params:{id:requestId},ifMatch:version,body:{approve,note:String(new FormData(e.currentTarget).get('note'))}});}}><AreaField label="Independent period review note" name="note" required minLength={10}/><div className="flex gap-2"><Button type="submit" value="approve" disabled={command.isPending}>Approve period change</Button><Button type="submit" value="reject" variant="ghost" disabled={command.isPending}>Reject period request</Button></div><ErrorNote e={command.error}/></form>;
}
