import {Inject,Injectable} from '@nestjs/common';
import {audit,Db,DomainError,expectVersion,isExternal,type RequestContext,type Tx} from '../platform';
import type {Permission} from '@dbl/contracts';
@Injectable()
export class GovernanceService {
 constructor(@Inject(Db)private db:Db){}
 private grants(c:RequestContext,p:Permission){const g=c.permissions.get(p)??[];if(isExternal(c)||!g.length)throw new DomainError('FORBIDDEN','Internal governance permission is required.');return g;}
 private scope(c:RequestContext,p:Permission,e:string,b:string|null){if(!this.grants(c,p).some(g=>(!g.legalEntityId||g.legalEntityId===e)&&(!g.branchId||g.branchId===b)))throw new DomainError('FORBIDDEN','Record is outside your governance scope.');}
 private pred(a:string){return `EXISTS(SELECT 1 FROM jsonb_array_elements($1::jsonb) g WHERE (g->>'legalEntityId' IS NULL OR g->>'legalEntityId'=${a}.legal_entity_id::text) AND(g->>'branchId' IS NULL OR g->>'branchId'=${a}.branch_id::text))`;}
 private async record(tx:Tx,c:RequestContext,table:'knowledge_revisions'|'risks',id:string,p:Permission,lock=false){const r=await tx.maybe(`SELECT * FROM collab.${table} WHERE id=$1 ${lock?'FOR UPDATE':''}`,[id]);if(!r)throw new DomainError('NOT_FOUND','Governance record not found.');this.scope(c,p,r.legal_entity_id,r.branch_id);return r;}
 knowledge(c:RequestContext,q:any){const g=this.grants(c,'work.view');return this.db.run(c,tx=>tx.q(`SELECT k.*,EXISTS(SELECT 1 FROM collab.knowledge_acknowledgements a WHERE a.revision_id=k.id AND a.membership_id=$4) AS acknowledged FROM collab.knowledge_revisions k WHERE ${this.pred('k')} AND(k.status='published' OR k.created_by=$4 OR EXISTS(SELECT 1 FROM jsonb_array_elements($5::jsonb) cg WHERE(cg->>'legalEntityId' IS NULL OR cg->>'legalEntityId'=k.legal_entity_id::text) AND(cg->>'branchId' IS NULL OR cg->>'branchId'=k.branch_id::text))) AND($2::text IS NULL OR k.title ILIKE '%'||$2||'%' OR k.content ILIKE '%'||$2||'%') AND($3::text IS NULL OR k.category=$3) ORDER BY k.key,k.revision DESC LIMIT 300`,[JSON.stringify(g),q.search??null,q.category??null,c.membershipId,JSON.stringify(c.permissions.get('work.configure')??[])]));}
 createKnowledge(c:RequestContext,b:any){this.scope(c,'work.manage',b.legalEntityId,b.branchId);return this.db.run(c,async tx=>{await tx.q(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[c.tenantId+':knowledge:'+b.legalEntityId+':'+b.branchId+':'+b.key]);const r=await tx.one(`INSERT INTO collab.knowledge_revisions(tenant_id,legal_entity_id,branch_id,key,title,category,revision,content,change_note,created_by) SELECT $1,$2,$3,$4,$5,$6,COALESCE(max(revision),0)+1,$7,$8,$9 FROM collab.knowledge_revisions WHERE key=$4 AND legal_entity_id=$2 AND branch_id IS NOT DISTINCT FROM $3::uuid RETURNING *`,[c.tenantId,b.legalEntityId,b.branchId,b.key,b.title,b.category,b.content,b.changeNote,c.membershipId]);await audit(tx,c,'knowledge.draft-created','knowledge_revision',r.id,{revision:r.revision,hash:r.content_sha256});return r;});}
 publish(c:RequestContext,id:string,b:any){this.grants(c,'work.configure');return this.db.run(c,async tx=>{const r=await this.record(tx,c,'knowledge_revisions',id,'work.configure',true);await tx.q(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[c.tenantId+':knowledge:'+r.legal_entity_id+':'+r.branch_id+':'+r.key]);if(await tx.maybe(`SELECT 1 FROM collab.knowledge_revisions WHERE key=$1 AND legal_entity_id=$2 AND branch_id IS NOT DISTINCT FROM $3::uuid AND revision>$4`,[r.key,r.legal_entity_id,r.branch_id,r.revision]))throw new DomainError('INVALID_STATE_TRANSITION','Publish the latest revision.');if(r.status!=='draft')throw new DomainError('INVALID_STATE_TRANSITION','Only a draft can be published.');if(r.created_by===c.membershipId)throw new DomainError('SEPARATION_OF_DUTIES','The author cannot publish their own revision.');const out=await tx.one(`UPDATE collab.knowledge_revisions SET status='published',published_by=$2,published_at=now(),review_note=$3 WHERE id=$1 RETURNING *`,[id,c.membershipId,b.reviewNote]);await audit(tx,c,'knowledge.published','knowledge_revision',id,{hash:r.content_sha256,reviewNote:b.reviewNote});return out;});}
 acknowledge(c:RequestContext,id:string){this.grants(c,'work.view');return this.db.run(c,async tx=>{const r=await this.record(tx,c,'knowledge_revisions',id,'work.view');if(r.status!=='published')throw new DomainError('INVALID_STATE_TRANSITION','Only a published revision can be acknowledged.');await tx.q(`INSERT INTO collab.knowledge_acknowledgements(tenant_id,revision_id,membership_id,content_sha256) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING`,[c.tenantId,id,c.membershipId,r.content_sha256]);await audit(tx,c,'knowledge.acknowledged','knowledge_revision',id,{hash:r.content_sha256});return {id,acknowledged:true,contentSha256:r.content_sha256};});}
 risks(c:RequestContext){const g=this.grants(c,'quality.view');return this.db.run(c,tx=>tx.q(`SELECT r.*,u.subject AS owner,r.next_review_on<CURRENT_DATE AND r.status<>'closed' AS review_overdue FROM collab.risks r JOIN platform.memberships m ON m.id=r.owner_membership_id JOIN platform.users u ON u.id=m.user_id WHERE ${this.pred('r')} ORDER BY(r.status='closed'),r.residual_score DESC,r.next_review_on LIMIT 300`,[JSON.stringify(g)]));}
 createRisk(c:RequestContext,b:any){this.scope(c,'quality.manage',b.legalEntityId,b.branchId);return this.db.run(c,async tx=>{if(!await tx.maybe(`SELECT 1 FROM platform.memberships m WHERE m.id=$1 AND m.status='active' AND m.workspace='staff' AND EXISTS(SELECT 1 FROM platform.membership_roles mr JOIN platform.role_permissions rp ON rp.tenant_id=mr.tenant_id AND rp.role_id=mr.role_id WHERE mr.membership_id=m.id AND rp.permission='quality.view' AND(mr.legal_entity_id IS NULL OR mr.legal_entity_id=$2) AND(mr.branch_id IS NULL OR mr.branch_id=$3))`,[b.ownerMembershipId,b.legalEntityId,b.branchId]))throw new DomainError('VALIDATION_FAILED','Risk owner must be active internal staff.');if(!(await tx.one(`SELECT $1::date>=CURRENT_DATE valid`,[b.nextReviewOn])).valid)throw new DomainError('VALIDATION_FAILED','Review date must not be in the past.');const r=await tx.one(`INSERT INTO collab.risks(tenant_id,legal_entity_id,branch_id,title,category,description,likelihood,impact,residual_likelihood,residual_impact,mitigation,owner_membership_id,next_review_on,created_by) VALUES($1,$2,$3,$4,$5,$6,$7::integer,$8::integer,$7::integer,$8::integer,$9,$10,$11,$12) RETURNING *`,[c.tenantId,b.legalEntityId,b.branchId,b.title,b.category,b.description,b.likelihood,b.impact,b.mitigation,b.ownerMembershipId,b.nextReviewOn,c.membershipId]);await audit(tx,c,'risk.created','risk',r.id,{score:r.inherent_score});return r;});}
 risk(c:RequestContext,id:string){this.grants(c,'quality.view');return this.db.run(c,async tx=>({...await this.record(tx,c,'risks',id,'quality.view'),reviews:await tx.q(`SELECT * FROM collab.risk_reviews WHERE risk_id=$1 ORDER BY reviewed_at DESC,id`,[id])}));}
 review(c:RequestContext,id:string,b:any){this.grants(c,'quality.hold.release');return this.db.run(c,async tx=>{const r=await this.record(tx,c,'risks',id,'quality.hold.release',true);expectVersion(r.version,c);if(r.status==='closed')throw new DomainError('INVALID_STATE_TRANSITION','Closed risks retain their final review. Create a new risk for a new exposure.');if(r.created_by===c.membershipId||r.owner_membership_id===c.membershipId)throw new DomainError('SEPARATION_OF_DUTIES','Risk authors and owners cannot independently review their own risk.');if(!(await tx.one(`SELECT $1::date>=CURRENT_DATE valid`,[b.nextReviewOn])).valid)throw new DomainError('VALIDATION_FAILED','Review date must not be in the past.');if(b.evidenceDocumentId&&!await tx.maybe(`SELECT 1 FROM platform.documents d JOIN platform.document_versions v ON v.document_id=d.id AND v.version_no=(SELECT max(version_no) FROM platform.document_versions WHERE document_id=d.id) WHERE d.id=$1 AND d.related_type='risk' AND d.related_id=$2 AND d.status='approved' AND v.scan_status='clean'`,[b.evidenceDocumentId,id]))throw new DomainError('DOCUMENT_NOT_CLEAN','Use approved clean evidence attached to this risk.');const review=await tx.one(`INSERT INTO collab.risk_reviews(tenant_id,risk_id,reviewed_by,outcome,review_note,mitigation,residual_likelihood,residual_impact,next_review_on,evidence_document_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id`,[c.tenantId,id,c.membershipId,b.outcome,b.reviewNote,b.mitigation,b.residualLikelihood,b.residualImpact,b.nextReviewOn,b.evidenceDocumentId]);const out=await tx.one(`UPDATE collab.risks SET status=$2,residual_likelihood=$3,residual_impact=$4,mitigation=$5,next_review_on=$6 WHERE id=$1 RETURNING *`,[id,b.outcome,b.residualLikelihood,b.residualImpact,b.mitigation,b.nextReviewOn]);await audit(tx,c,'risk.reviewed','risk',id,{reviewId:review.id,from:r.residual_score,to:out.residual_score,outcome:b.outcome});return out;});}
}
