import { z } from 'zod';

export const ERROR_CODES = [
  'SERVICE_UNAVAILABLE',
  'UNAUTHENTICATED', 'FORBIDDEN', 'TENANT_REQUIRED', 'NOT_FOUND', 'VALIDATION_FAILED', 'VERSION_CONFLICT',
  'IDEMPOTENCY_KEY_REUSED', 'IDEMPOTENCY_KEY_REQUIRED', 'INVALID_STATE_TRANSITION', 'DUPLICATE',
  'ACCOUNTING_PERIOD_CLOSED', 'PERIOD_NOT_FOUND', 'INSUFFICIENT_STOCK', 'STOCK_ON_HOLD', 'RELEASE_EVIDENCE_REQUIRED',
  'SEPARATION_OF_DUTIES', 'OVER_ALLOCATION', 'JOB_NOT_CLOSABLE', 'CURRENCY_MISMATCH', 'DOCUMENT_NOT_CLEAN',
  'WEBHOOK_SIGNATURE_INVALID', 'AI_TOOL_DENIED', 'AI_BUDGET_EXCEEDED', 'BOOKING_OUTCOME_UNKNOWN', 'QUALIFICATION_REQUIRED', 'RATE_LIMITED', 'INTERNAL',
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];

export const ApiErrorSchema = z.object({
  code: z.enum(ERROR_CODES), message: z.string(), requestId: z.string(), details: z.record(z.unknown()).optional(),
});
export type ApiErrorBody = z.infer<typeof ApiErrorSchema>;
export const HTTP_STATUS: Record<ErrorCode, number> = {
  SERVICE_UNAVAILABLE:503,
  UNAUTHENTICATED: 401, FORBIDDEN: 403, TENANT_REQUIRED: 400, NOT_FOUND: 404, VALIDATION_FAILED: 422, VERSION_CONFLICT: 409,
  IDEMPOTENCY_KEY_REUSED: 422, IDEMPOTENCY_KEY_REQUIRED: 400, INVALID_STATE_TRANSITION: 409, DUPLICATE: 409,
  ACCOUNTING_PERIOD_CLOSED: 422, PERIOD_NOT_FOUND: 422, INSUFFICIENT_STOCK: 409, STOCK_ON_HOLD: 409, RELEASE_EVIDENCE_REQUIRED: 422,
  SEPARATION_OF_DUTIES: 403, OVER_ALLOCATION: 422, JOB_NOT_CLOSABLE: 409, CURRENCY_MISMATCH: 422, DOCUMENT_NOT_CLEAN: 422,
  WEBHOOK_SIGNATURE_INVALID: 401, AI_TOOL_DENIED: 403, AI_BUDGET_EXCEEDED: 429, BOOKING_OUTCOME_UNKNOWN: 409, QUALIFICATION_REQUIRED: 422, RATE_LIMITED: 429, INTERNAL: 500,
};
