import {Inject,Injectable} from '@nestjs/common';
import {createHash} from 'node:crypto';
import type {Permission} from '@dbl/contracts';
import {audit,Db,DomainError,emit,expectVersion,isExternal,type RequestContext,type Tx} from '../../platform';
@Injectable()
export class PeriodService{
 constructor(@Inject(Db)private db:Db){}
 private grants(c:RequestContext,p:Permission){const g=(c.permissions.get(p)??[]).filter(x=>x.branchId===null);if(isExternal(c)||!g.length)throw new DomainError('FORBIDDEN','Internal legal-entity finance permission is required.');return g;}
 private scope(c:RequestContext,p:Permission,e:string){if(!this.grants(c,p).some(g=>g.legalEntityId===null||g.legalEntityId===e))throw new DomainError('FORBIDDEN','Period is outside your finance scope.');}
 private async period(tx:Tx,c:RequestContext,id:string,p:Permission,lock=false){const r=await tx.maybe(`SELECT * FROM finance.accounting_periods WHERE id=$1 ${lock?'FOR UPDATE':''}`,[id]);if(!r)throw new DomainError('NOT_FOUND','Accounting period not found.');this.scope(c,p,r.legal_entity_id);return r;}
 list(c:RequestContext){const g=this.grants(c,'finance.period.view');return this.db.run(c,tx=>tx.q(`SELECT p.*,e.name AS legal_entity FROM finance.accounting_periods p JOIN org.legal_entities e ON e.id=p.legal_entity_id WHERE $1::boolean OR p.legal_entity_id=ANY($2::uuid[]) ORDER BY p.start_date DESC,e.name`,[g.some(x=>x.legalEntityId===null),g.map(x=>x.legalEntityId).filter(Boolean)]));}
 private async snapshot(tx:Tx,p:any){
  const balances=await tx.q(`SELECT j.currency,a.code,a.name,sum(l.debit)::text AS debit,sum(l.credit)::text AS credit,(sum(l.debit)-sum(l.credit))::text AS balance FROM finance.journals j JOIN finance.journal_lines l ON l.journal_id=j.id JOIN finance.accounts a ON a.id=l.account_id WHERE j.legal_entity_id=$1 AND j.posting_date BETWEEN $2 AND $3 GROUP BY j.currency,a.code,a.name ORDER BY j.currency,a.code`,[p.legal_entity_id,p.start_date,p.end_date]);
  const journals=await tx.q(`SELECT j.id,j.ref,j.created_at,EXISTS(SELECT 1 FROM finance.journal_lines l WHERE l.journal_id=j.id) AS has_lines FROM finance.journals j WHERE j.legal_entity_id=$1 AND j.posting_date BETWEEN $2 AND $3 ORDER BY j.id`,[p.legal_entity_id,p.start_date,p.end_date]);
  const drafts=await tx.q(`SELECT id,status,version FROM finance.invoices WHERE legal_entity_id=$1 AND status IN ('draft','approved') AND (posting_date BETWEEN $2 AND $3 OR posting_date IS NULL AND created_at::date<=$3) ORDER BY id`,[p.legal_entity_id,p.start_date,p.end_date]);
  const unbalanced=await tx.q(`SELECT j.id FROM finance.journals j LEFT JOIN finance.journal_lines l ON l.journal_id=j.id WHERE j.legal_entity_id=$1 AND j.posting_date BETWEEN $2 AND $3 GROUP BY j.id HAVING count(l.id)=0 OR COALESCE(sum(l.debit-l.credit),0)<>0`,[p.legal_entity_id,p.start_date,p.end_date]);
  const hash=createHash('sha256').update(JSON.stringify({balances,journals,drafts})).digest('hex');return {hash,balances,journalCount:journals.length,unpostedInvoices:drafts.length,invalidJournals:unbalanced.length};
 }
 detail(c:RequestContext,id:string){this.grants(c,'finance.period.view');return this.db.run(c,async tx=>{const p=await this.period(tx,c,id,'finance.period.view');return {...p,trialBalance:await this.snapshot(tx,p),requests:await tx.q(`SELECT * FROM finance.period_requests WHERE period_id=$1 ORDER BY requested_at DESC,id`,[id])};});}
 request(c:RequestContext,id:string,b:any){this.grants(c,'finance.period.request');return this.db.run(c,async tx=>{
  const p=await this.period(tx,c,id,'finance.period.request',true);expectVersion(p.version,c);if(b.kind==='close'&&p.status!=='open'||b.kind==='reopen'&&p.status!=='closed')throw new DomainError('INVALID_STATE_TRANSITION','Request does not match the period state.');
  if(b.kind==='close'&&!(await tx.one(`SELECT $1::date<CURRENT_DATE ended`,[p.end_date])).ended)throw new DomainError('INVALID_STATE_TRANSITION','Only an ended period can be closed.');
  const snapshot=await this.snapshot(tx,p);if(b.kind==='close'&&(snapshot.invalidJournals||snapshot.unpostedInvoices))throw new DomainError('VALIDATION_FAILED','Resolve unposted invoices and invalid journals before closing.',{unpostedInvoices:snapshot.unpostedInvoices,invalidJournals:snapshot.invalidJournals});
  const r=await tx.one(`INSERT INTO finance.period_requests(tenant_id,period_id,kind,reason,requested_by,snapshot) VALUES($1,$2,$3,$4,$5,$6::jsonb) RETURNING *`,[c.tenantId,id,b.kind,b.reason,c.membershipId,JSON.stringify(snapshot)]);await audit(tx,c,'period.'+b.kind+'-requested','accounting_period',id,{requestId:r.id,snapshotHash:snapshot.hash,reason:b.reason});return r;
 });}
 decide(c:RequestContext,id:string,b:any){this.grants(c,'finance.period.decide');return this.db.run(c,async tx=>{
  const initial=await tx.maybe(`SELECT period_id FROM finance.period_requests WHERE id=$1`,[id]);if(!initial)throw new DomainError('NOT_FOUND','Period request not found.');const p=await this.period(tx,c,initial.period_id,'finance.period.decide',true);expectVersion(p.version,c);const r=await tx.one(`SELECT * FROM finance.period_requests WHERE id=$1 FOR UPDATE`,[id]);if(r.status!=='pending')throw new DomainError('INVALID_STATE_TRANSITION','Period request already decided.');if(r.requested_by===c.membershipId)throw new DomainError('SEPARATION_OF_DUTIES','Requesters cannot decide their own period change.');
  if(b.approve){if(r.kind==='close'&&p.status!=='open'||r.kind==='reopen'&&p.status!=='closed')throw new DomainError('INVALID_STATE_TRANSITION','Period changed since request.');const snapshot=await this.snapshot(tx,p);if(snapshot.hash!==r.snapshot.hash)throw new DomainError('VERSION_CONFLICT','Ledger changed since request. Reject it and prepare a new reviewed snapshot.');if(r.kind==='close'&&(snapshot.invalidJournals||snapshot.unpostedInvoices))throw new DomainError('VALIDATION_FAILED','Period reconciliation blockers remain.');}
  const out=await tx.one(`UPDATE finance.period_requests SET status=$2,decided_by=$3,decided_at=now(),decision_note=$4 WHERE id=$1 RETURNING *`,[id,b.approve?'approved':'rejected',c.membershipId,b.note]);if(b.approve)await tx.q(`UPDATE finance.accounting_periods SET status=$2 WHERE id=$1`,[p.id,r.kind==='close'?'closed':'open']);await audit(tx,c,'period.request-decided','accounting_period',p.id,{requestId:id,kind:r.kind,approved:b.approve,note:b.note});await emit(tx,c,'AccountingPeriodDecided','accounting_period',p.id,{kind:r.kind,approved:b.approve});return out;
 });}
}
