import { Inject, Injectable } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { addBusinessSeconds, businessSecondsBetween } from '@dbl/contracts';
import { audit, Db, DomainError, emit, expectVersion, isExternal, type RequestContext, type Tx } from '../platform';
import type { Permission } from '@dbl/contracts';

@Injectable()
export class WorkService {
 constructor(@Inject(Db) private db:Db) {}
 private grants(ctx:RequestContext,p:Permission) {const grants=ctx.permissions.get(p)??[];if(isExternal(ctx)||!grants.length)throw new DomainError('FORBIDDEN','Internal work permission is required.');return grants;}
 private scope(ctx:RequestContext,p:Permission,entity:string,branch:string|null) {if(!this.grants(ctx,p).some(g=>(!g.legalEntityId||g.legalEntityId===entity)&&(!g.branchId||g.branchId===branch)))throw new DomainError('FORBIDDEN','Work is outside your entity or branch scope.');}
 private predicate(alias:string,param:number) {return `EXISTS(SELECT 1 FROM jsonb_array_elements($${param}::jsonb) g WHERE (g->>'legalEntityId' IS NULL OR g->>'legalEntityId'=${alias}.legal_entity_id::text) AND (g->>'branchId' IS NULL OR g->>'branchId'=${alias}.branch_id::text))`;}
 private global(ctx:RequestContext) {if(!this.grants(ctx,'work.configure').some(g=>!g.legalEntityId&&!g.branchId))throw new DomainError('FORBIDDEN','Tenant-wide work configuration permission is required.');}
 private async member(tx:Tx,id:string,entity:string,branch:string|null) {
  const m=await tx.maybe(`SELECT m.id FROM platform.memberships m WHERE m.id=$1 AND m.status='active' AND m.workspace='staff' AND EXISTS(SELECT 1 FROM platform.membership_roles mr JOIN platform.role_permissions rp ON rp.tenant_id=mr.tenant_id AND rp.role_id=mr.role_id WHERE mr.membership_id=m.id AND rp.permission='work.manage' AND (mr.legal_entity_id IS NULL OR mr.legal_entity_id=$2) AND (mr.branch_id IS NULL OR mr.branch_id=$3))`,[id,entity,branch]);
  if(!m)throw new DomainError('VALIDATION_FAILED','Assignee must be an active staff member with work access to this scope.');return m;
 }
 private async validateScope(tx:Tx,entity:string,branch:string|null) {
  if(!await tx.maybe(`SELECT 1 FROM org.legal_entities WHERE id=$1`,[entity]) || branch&&!await tx.maybe(`SELECT 1 FROM org.branches WHERE id=$1 AND legal_entity_id=$2`,[branch,entity]))throw new DomainError('VALIDATION_FAILED','Entity or branch not found.');
 }
 private async item(tx:Tx,ctx:RequestContext,id:string,p:Permission,lock=false) {
  const r=await tx.maybe(`SELECT i.*,c.calendar FROM collab.work_items i JOIN collab.work_calendars c ON c.id=i.calendar_id WHERE i.id=$1 ${lock?'FOR UPDATE OF i':''}`,[id]);if(!r)throw new DomainError('NOT_FOUND','Work item not found.');this.scope(ctx,p,r.legal_entity_id,r.branch_id);return r;
 }
 private async now(tx:Tx) {return new Date((await tx.one(`SELECT now() at`)).at);}
 calendars(ctx:RequestContext) {this.grants(ctx,'work.view');return this.db.run(ctx,tx=>tx.q(`SELECT * FROM collab.work_calendars ORDER BY key,version DESC`));}
 createCalendar(ctx:RequestContext,b:any) {this.global(ctx);return this.db.run(ctx,async tx=>{
  await tx.q(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[ctx.tenantId+':calendar:'+b.key]);
  const r=await tx.one(`INSERT INTO collab.work_calendars(tenant_id,key,name,version,calendar,created_by) SELECT $1,$2,$3,COALESCE(max(version),0)+1,$4::jsonb,$5 FROM collab.work_calendars WHERE key=$2 RETURNING *`,[ctx.tenantId,b.key,b.name,JSON.stringify(b.calendar),ctx.membershipId]);await audit(tx,ctx,'work.calendar-created','work_calendar',r.id,{version:r.version});return r;
 });}
 templates(ctx:RequestContext) {const grants=this.grants(ctx,'work.view');return this.db.run(ctx,tx=>tx.q(`SELECT t.* FROM collab.work_templates t WHERE ${this.predicate('t',1)} ORDER BY key,version DESC`,[JSON.stringify(grants)]));}
 createTemplate(ctx:RequestContext,b:any) {this.scope(ctx,'work.configure',b.legalEntityId,b.branchId);return this.db.run(ctx,async tx=>{
  await this.validateScope(tx,b.legalEntityId,b.branchId);await tx.q(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[ctx.tenantId+':template:'+b.legalEntityId+':'+b.branchId+':'+b.key]);
  const r=await tx.one(`INSERT INTO collab.work_templates(tenant_id,legal_entity_id,branch_id,key,name,version,calendar_id,steps,created_by) SELECT $1,$2,$3,$4,$5,COALESCE(max(version),0)+1,$6,$7::jsonb,$8 FROM collab.work_templates WHERE legal_entity_id=$2 AND branch_id IS NOT DISTINCT FROM $3::uuid AND key=$4 RETURNING *`,[ctx.tenantId,b.legalEntityId,b.branchId,b.key,b.name,b.calendarId,JSON.stringify(b.steps),ctx.membershipId]);await audit(tx,ctx,'work.template-created','work_template',r.id,{version:r.version});return r;
 });}
 private async insert(tx:Tx,ctx:RequestContext,b:any,calendar:any,extras:{templateId?:string,instanceId?:string,stepKey?:string,dependsOn?:string[]}={}) {
  if(b.assigneeMembershipId)await this.member(tx,b.assigneeMembershipId,b.legalEntityId,b.branchId);
  const blocked=!!extras.dependsOn?.length,seconds=b.slaMinutes*60,due=blocked?null:addBusinessSeconds(await this.now(tx),seconds,calendar);
  const r=await tx.one(`INSERT INTO collab.work_items(tenant_id,legal_entity_id,branch_id,title,description,department,priority,complexity,assignee_membership_id,created_by,calendar_id,sla_seconds,remaining_seconds,due_at,status,template_id,instance_id,step_key,depends_on) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::integer,$12::integer,$13,$14,$15,$16,$17,$18) RETURNING *`,[ctx.tenantId,b.legalEntityId,b.branchId,b.title,b.description,b.department,b.priority??'normal',b.complexity,b.assigneeMembershipId,ctx.membershipId,b.calendarId,seconds,due,blocked?'blocked':'open',extras.templateId??null,extras.instanceId??null,extras.stepKey??null,extras.dependsOn??[]]);await audit(tx,ctx,'work.created','work_item',r.id);await emit(tx,ctx,'WorkCreated','work_item',r.id,{department:r.department,assigneeMembershipId:r.assignee_membership_id});return r;
 }
 create(ctx:RequestContext,b:any) {this.scope(ctx,'work.manage',b.legalEntityId,b.branchId);return this.db.run(ctx,async tx=>{await this.validateScope(tx,b.legalEntityId,b.branchId);const c=await tx.maybe(`SELECT calendar FROM collab.work_calendars WHERE id=$1`,[b.calendarId]);if(!c)throw new DomainError('VALIDATION_FAILED','Calendar not found.');return this.insert(tx,ctx,b,c.calendar);});}
 startTemplate(ctx:RequestContext,b:any) {this.grants(ctx,'work.manage');return this.db.run(ctx,async tx=>{
  const t=await tx.maybe(`SELECT t.*,c.calendar FROM collab.work_templates t JOIN collab.work_calendars c ON c.id=t.calendar_id WHERE t.id=$1`,[b.templateId]);if(!t)throw new DomainError('NOT_FOUND','Template not found.');this.scope(ctx,'work.manage',t.legal_entity_id,t.branch_id);
  const instanceId=randomUUID(),items=[];for(const s of t.steps)items.push(await this.insert(tx,ctx,{legalEntityId:t.legal_entity_id,branchId:t.branch_id,calendarId:t.calendar_id,title:`${b.title} · ${s.title}`,description:`${t.name}, version ${t.version}: ${s.title}`,department:s.department,slaMinutes:s.slaMinutes,complexity:s.complexity,assigneeMembershipId:b.assigneeMembershipId},t.calendar,{templateId:t.id,instanceId,stepKey:s.key,dependsOn:s.dependsOn}));return {instanceId,items};
 });}
 list(ctx:RequestContext,q:any) {const grants=this.grants(ctx,'work.view');return this.db.run(ctx,tx=>tx.q(`SELECT i.*,u.subject AS assignee,(i.due_at<now() AND i.status IN ('open','in_progress')) AS overdue FROM collab.work_items i LEFT JOIN platform.memberships m ON m.id=i.assignee_membership_id LEFT JOIN platform.users u ON u.id=m.user_id WHERE ${this.predicate('i',1)} AND ($2::text IS NULL OR i.department=$2) AND ($3::text IS NULL OR i.status=$3) AND (NOT $4::boolean OR i.assignee_membership_id=$5) ORDER BY (i.priority='critical') DESC,(i.due_at<now()) DESC,i.due_at NULLS LAST,i.created_at DESC LIMIT 500`,[JSON.stringify(grants),q.department??null,q.status??null,q.mine==='true',ctx.membershipId]));}
 get(ctx:RequestContext,id:string) {this.grants(ctx,'work.view');return this.db.run(ctx,async tx=>{const r=await this.item(tx,ctx,id,'work.view');return {...r,history:await tx.q(`SELECT action,at,detail FROM platform.audit_events WHERE entity_type='work_item' AND entity_id=$1 ORDER BY id`,[id])};});}
 transition(ctx:RequestContext,id:string,b:any) {this.grants(ctx,'work.manage');return this.db.run(ctx,async tx=>{
  const initial=await this.item(tx,ctx,id,'work.manage');if(initial.instance_id)await tx.q(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[initial.instance_id]);const r=await this.item(tx,ctx,id,'work.manage',true);expectVersion(r.version,ctx);
  const allowed:Record<string,string[]>={start:['open'],pause:['open','in_progress'],resume:['waiting'],complete:['in_progress'],cancel:['blocked','open','in_progress','waiting']};
  if(!allowed[b.action].includes(r.status))throw new DomainError('INVALID_STATE_TRANSITION',`Cannot ${b.action} ${r.status} work.`);
  const status:Record<string,string>={start:'in_progress',pause:'waiting',resume:'in_progress',complete:'done',cancel:'cancelled'};const now=await this.now(tx),remaining=b.action==='pause'?businessSecondsBetween(now,new Date(r.due_at),r.calendar):Number(r.remaining_seconds),due=b.action==='resume'?addBusinessSeconds(now,remaining,r.calendar):['complete','cancel','pause'].includes(b.action)?null:r.due_at;
  const breached=!r.breached_at&&r.due_at&&new Date(r.due_at)<now;
  const out=await tx.one(`UPDATE collab.work_items SET status=$2,remaining_seconds=$3,due_at=$4,paused_at=$5,completed_at=$6,completed_by=$7,breached_at=COALESCE(breached_at,$8) WHERE id=$1 RETURNING *`,[id,status[b.action],remaining,due,b.action==='pause'?now:null,['complete','cancel'].includes(b.action)?now:null,['complete','cancel'].includes(b.action)?ctx.membershipId:null,breached?now:null]);
  if(breached){await audit(tx,ctx,'work.sla-breached','work_item',id,{dueAt:r.due_at});await emit(tx,ctx,'WorkSlaBreached','work_item',id,{department:r.department,assigneeMembershipId:r.assignee_membership_id});}
  await audit(tx,ctx,'work.'+b.action,'work_item',id,{note:b.note});await emit(tx,ctx,'WorkStateChanged','work_item',id,{from:r.status,to:out.status});
  if(b.action==='complete'&&r.instance_id){const blocked=await tx.q(`SELECT * FROM collab.work_items WHERE instance_id=$1 AND status='blocked' ORDER BY id FOR UPDATE`,[r.instance_id]);for(const next of blocked){const unfinished=await tx.maybe(`SELECT 1 FROM collab.work_items WHERE instance_id=$1 AND step_key=ANY($2::text[]) AND status<>'done'`,[r.instance_id,next.depends_on]);if(!unfinished){await tx.q(`UPDATE collab.work_items SET status='open',due_at=$2 WHERE id=$1`,[next.id,addBusinessSeconds(now,Number(next.remaining_seconds),r.calendar)]);await audit(tx,ctx,'work.dependency-released','work_item',next.id,{completedItemId:id});}}}
  return out;
 });}
 assign(ctx:RequestContext,id:string,b:any) {this.grants(ctx,'work.manage');return this.db.run(ctx,async tx=>{const r=await this.item(tx,ctx,id,'work.manage',true);expectVersion(r.version,ctx);if(['done','cancelled'].includes(r.status))throw new DomainError('INVALID_STATE_TRANSITION','Closed work cannot be reassigned.');if(b.assigneeMembershipId)await this.member(tx,b.assigneeMembershipId,r.legal_entity_id,r.branch_id);const out=await tx.one(`UPDATE collab.work_items SET assignee_membership_id=$2 WHERE id=$1 RETURNING *`,[id,b.assigneeMembershipId]);await audit(tx,ctx,'work.reassigned','work_item',id,{from:r.assignee_membership_id,to:b.assigneeMembershipId,reason:b.reason});return out;});}
 directory(ctx:RequestContext) {const grants=this.grants(ctx,'work.view');return this.db.run(ctx,async tx=>({membershipId:ctx.membershipId,entities:await tx.q(`SELECT e.id,e.name FROM org.legal_entities e WHERE EXISTS(SELECT 1 FROM jsonb_array_elements($1::jsonb) g WHERE g->>'legalEntityId' IS NULL OR g->>'legalEntityId'=e.id::text) ORDER BY e.name`,[JSON.stringify(grants)]),branches:await tx.q(`SELECT b.id,b.name,b.legal_entity_id FROM org.branches b WHERE ${this.predicate('b',1).replace(/b\.branch_id/g,'b.id')} ORDER BY b.name`,[JSON.stringify(grants)]),members:await tx.q(`SELECT m.id,u.subject,u.display_name FROM platform.memberships m JOIN platform.users u ON u.id=m.user_id WHERE m.status='active' AND m.workspace='staff' ORDER BY u.subject`)}));}
 capacity(ctx:RequestContext,b:any) {this.scope(ctx,'work.configure',b.legalEntityId,b.branchId);return this.db.run(ctx,async tx=>{await this.validateScope(tx,b.legalEntityId,b.branchId);await this.member(tx,b.membershipId,b.legalEntityId,b.branchId);const r=await tx.one(`INSERT INTO collab.work_capacities(tenant_id,legal_entity_id,branch_id,membership_id,department,capacity_points,available) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(tenant_id,legal_entity_id,branch_id,membership_id,department) DO UPDATE SET capacity_points=EXCLUDED.capacity_points,available=EXCLUDED.available RETURNING *`,[ctx.tenantId,b.legalEntityId,b.branchId,b.membershipId,b.department,b.capacityPoints,b.available]);await audit(tx,ctx,'work.capacity-set','membership',b.membershipId,{department:b.department,points:b.capacityPoints,available:b.available});return r;});}
 workload(ctx:RequestContext) {const grants=this.grants(ctx,'work.view');return this.db.run(ctx,tx=>tx.q(`SELECT c.*,u.subject AS member,m.status AS membership_status,COALESCE(w.open_count,0)::int AS open_count,COALESCE(w.points,0)::int AS assigned_points,COALESCE(w.overdue,0)::int AS overdue_count,round(COALESCE(w.points,0)*100.0/c.capacity_points,1) AS utilization_percent FROM collab.work_capacities c JOIN platform.memberships m ON m.id=c.membership_id JOIN platform.users u ON u.id=m.user_id LEFT JOIN LATERAL(SELECT count(*) AS open_count,sum(i.complexity) AS points,count(*) FILTER(WHERE i.due_at<now()) AS overdue FROM collab.work_items i WHERE i.assignee_membership_id=c.membership_id AND i.legal_entity_id=c.legal_entity_id AND i.branch_id IS NOT DISTINCT FROM c.branch_id AND i.department=c.department AND i.status NOT IN ('done','cancelled')) w ON true WHERE ${this.predicate('c',1)} ORDER BY c.department,utilization_percent,c.membership_id`,[JSON.stringify(grants)]));}
 checkSlas(ctx:RequestContext) {const grants=this.grants(ctx,'work.manage');return this.db.run(ctx,async tx=>{const items=await tx.q(`SELECT i.* FROM collab.work_items i WHERE ${this.predicate('i',1)} AND i.status IN ('open','in_progress') AND i.due_at<now() AND i.breached_at IS NULL ORDER BY i.id FOR UPDATE SKIP LOCKED LIMIT 200`,[JSON.stringify(grants)]);for(const i of items){await tx.q(`UPDATE collab.work_items SET breached_at=now() WHERE id=$1`,[i.id]);await audit(tx,ctx,'work.sla-breached','work_item',i.id,{dueAt:i.due_at});await emit(tx,ctx,'WorkSlaBreached','work_item',i.id,{department:i.department,assigneeMembershipId:i.assignee_membership_id});}return {breachesRecorded:items.length};});}
 handovers(ctx:RequestContext) {this.grants(ctx,'work.view');return this.db.run(ctx,async tx=>{
  const rows=await tx.q(`SELECT * FROM collab.shift_handovers WHERE sender_membership_id=$1 OR recipient_membership_id=$1 ORDER BY created_at DESC LIMIT 100`,[ctx.membershipId]);const out=[];
  for(const h of rows){const lines=await tx.q(`SELECT i.id,i.title,i.department,i.status,i.version,i.legal_entity_id,i.branch_id,hi.item_version FROM collab.handover_items hi JOIN collab.work_items i ON i.id=hi.work_item_id WHERE hi.handover_id=$1 AND ${this.predicate('i',2)}`,[h.id,JSON.stringify(this.grants(ctx,'work.view'))]);const count=await tx.one(`SELECT count(*)::int n FROM collab.handover_items WHERE handover_id=$1`,[h.id]);out.push({...h,note:count.n===lines.length?h.note:'Some items are outside your current access scope.',acknowledgement_note:count.n===lines.length?h.acknowledgement_note:null,items:lines,redactedItems:count.n-lines.length});}return out;
 });}
 createHandover(ctx:RequestContext,b:any) {this.grants(ctx,'work.manage');return this.db.run(ctx,async tx=>{
  if(b.recipientMembershipId===ctx.membershipId)throw new DomainError('SEPARATION_OF_DUTIES','Handover requires a different recipient.');
  const lines=await tx.q(`SELECT * FROM collab.work_items WHERE id=ANY($1::uuid[]) ORDER BY id FOR UPDATE`,[b.itemIds]);if(lines.length!==b.itemIds.length)throw new DomainError('NOT_FOUND','Work item not found.');
  for(const i of lines){this.scope(ctx,'work.manage',i.legal_entity_id,i.branch_id);if(i.assignee_membership_id!==ctx.membershipId||['done','cancelled'].includes(i.status))throw new DomainError('INVALID_STATE_TRANSITION','Hand over only your assigned outstanding work.');await this.member(tx,b.recipientMembershipId,i.legal_entity_id,i.branch_id);}
  const h=await tx.one(`INSERT INTO collab.shift_handovers(tenant_id,sender_membership_id,recipient_membership_id,note) VALUES($1,$2,$3,$4) RETURNING *`,[ctx.tenantId,ctx.membershipId,b.recipientMembershipId,b.note]);for(const i of lines)await tx.q(`INSERT INTO collab.handover_items(tenant_id,handover_id,work_item_id,item_version) VALUES($1,$2,$3,$4)`,[ctx.tenantId,h.id,i.id,i.version]);await audit(tx,ctx,'work.handover-created','shift_handover',h.id,{itemIds:b.itemIds,recipient:b.recipientMembershipId});await emit(tx,ctx,'WorkHandoverRequested','shift_handover',h.id,{recipientMembershipId:b.recipientMembershipId});return h;
 });}
 acknowledge(ctx:RequestContext,id:string,b:any) {this.grants(ctx,'work.manage');return this.db.run(ctx,async tx=>{
  const h=await tx.maybe(`SELECT * FROM collab.shift_handovers WHERE id=$1 AND recipient_membership_id=$2 FOR UPDATE`,[id,ctx.membershipId]);if(!h)throw new DomainError('NOT_FOUND','Handover not found.');expectVersion(h.version,ctx);if(h.status!=='pending')throw new DomainError('INVALID_STATE_TRANSITION','Handover already acknowledged.');
  const lines=await tx.q(`SELECT i.*,hi.item_version FROM collab.handover_items hi JOIN collab.work_items i ON i.id=hi.work_item_id WHERE hi.handover_id=$1 ORDER BY i.id FOR UPDATE OF i`,[id]);
  for(const i of lines){this.scope(ctx,'work.manage',i.legal_entity_id,i.branch_id);await this.member(tx,ctx.membershipId,i.legal_entity_id,i.branch_id);if(i.version!==i.item_version||i.assignee_membership_id!==h.sender_membership_id||['done','cancelled'].includes(i.status))throw new DomainError('VERSION_CONFLICT','Work changed since handover. Ask the sender to prepare a new handover.');}
  for(const i of lines){await tx.q(`UPDATE collab.work_items SET assignee_membership_id=$2 WHERE id=$1`,[i.id,ctx.membershipId]);await audit(tx,ctx,'work.handover-assigned','work_item',i.id,{handoverId:id,from:h.sender_membership_id,to:ctx.membershipId});}
  const out=await tx.one(`UPDATE collab.shift_handovers SET status='acknowledged',acknowledged_at=now(),acknowledgement_note=$2 WHERE id=$1 RETURNING *`,[id,b.note]);await audit(tx,ctx,'work.handover-acknowledged','shift_handover',id,{note:b.note});await emit(tx,ctx,'WorkHandoverAcknowledged','shift_handover',id,{recipientMembershipId:ctx.membershipId});return out;
 });}
}
