'use client';
import Link from 'next/link';
import { useMemo } from 'react';
import { createColumnHelper } from '@tanstack/react-table';
import { useForm } from 'react-hook-form';
import { Button, Card, Chip, PdfLink } from '@dbl/ui';
import { useCmd, useOp, money } from '@/lib/hooks';
import { ErrorNote, PageTitle, StatusChip } from '@/components/bits';
import { DataTable, Mono, RefLink, fmtDate } from '@/components/DataTable';
import { EntityPicker, FormGrid, JobPicker, PartyPicker, SelectField, TextField } from '@/components/fields';
import { SectionTabs } from '@/components/SectionTabs';

const ic = createColumnHelper<any>(), pc = createColumnHelper<any>(), bc = createColumnHelper<any>(), cc = createColumnHelper<any>();
const today = () => new Date().toISOString().slice(0, 10);

function Invoices() {
  const q = useOp('listInvoices'); const approve = useCmd('approveInvoice', { invalidate: ['listInvoices'] }); const post = useCmd('postInvoice', { invalidate: ['listInvoices', 'getOwnerOverview'] });
  const columns = useMemo(() => [ic.accessor('ref', { header: 'Invoice', cell: (c) => <Mono>{c.getValue() ?? 'draft'}</Mono> }), ic.accessor('job_id', { header: 'Job', cell: (c) => <RefLink href={`/jobs/${c.getValue()}`}>open</RefLink> }), ic.accessor('status', { header: 'Billing', cell: (c) => <StatusChip s={c.getValue()} /> }), ic.accessor('einvoice_status', { header: 'E-invoice', cell: (c) => <StatusChip s={c.getValue() ?? 'not_submitted'} /> }),
    ic.accessor('total', { header: 'Total', cell: (c) => money(c.getValue(), c.row.original.currency) }), ic.accessor((r) => Number(r.total) - Number(r.amount_allocated), { id: 'open', header: 'Open', cell: (c) => money(c.getValue(), c.row.original.currency) }), ic.accessor('due_date', { header: 'Due', cell: (c) => fmtDate(c.getValue()) }),
    ic.display({ id: 'a', header: '', cell: (c) => { const i = c.row.original; return <span className="flex gap-1.5"><PdfLink href={`/api/proxy/api/v1/invoices/${i.id}/pdf`} testId="invoice-pdf">PDF</PdfLink>{i.status === 'draft' ? <Button size="sm" variant="ghost" onClick={() => approve.mutate({ params: { id: i.id }, ifMatch: i.version })}>Approve</Button> : i.status === 'approved' ? <Button size="sm" onClick={() => post.mutate({ params: { id: i.id }, body: { postingDate: today() }, ifMatch: i.version })}>Post to ledger</Button> : null}</span>; } })], [approve, post]);
  return <Card title="Invoices"><DataTable q={q} columns={columns} empty="No invoices yet." label="Filter invoices" /><ErrorNote e={approve.error ?? post.error} /><p className="mt-3 text-xs text-steel">Billing → ledger → e-invoice are separate states. A different person must approve than drafted.</p></Card>;
}
function Payments() {
  const q = useOp('listPayments'); const inv = useOp('listInvoices'); const rec = useCmd('recordPayment', { invalidate: ['listPayments'] }); const alloc = useCmd('allocatePayment', { invalidate: ['listPayments', 'listInvoices'] });
  const f = useForm<any>({ defaultValues: { currency: 'AED', receivedOn: today() } }); const g = useForm<any>(); const open = ((inv.data as any[]) ?? []).filter((i) => i.status === 'posted' && Number(i.total) > Number(i.amount_allocated)); const withRoom = ((q.data as any[]) ?? []).filter((p) => Number(p.available) > 0);
  const columns = useMemo(() => [pc.accessor('party', { header: 'Customer' }), pc.accessor('amount', { header: 'Received', cell: (c) => money(c.getValue(), c.row.original.currency) }), pc.accessor('available', { header: 'Unallocated', cell: (c) => Number(c.getValue()) > 0 ? <Chip tone="hold">{money(c.getValue(), c.row.original.currency)}</Chip> : <Chip tone="ok">fully allocated</Chip> }), pc.accessor('received_on', { header: 'Date', cell: (c) => fmtDate(c.getValue()) }), pc.accessor('bank_reference', { header: 'Bank ref.', cell: (c) => <Mono>{c.getValue() ?? '—'}</Mono> })], []);
  return (<div className="grid grid-cols-1 lg:grid-cols-[1fr_360px] items-start gap-5"><Card title="Customer receipts"><DataTable q={q} columns={columns} empty="No receipts recorded." label="Filter receipts" /></Card>
    <div className="grid gap-5"><Card title="Record receipt"><form className="grid gap-3" onSubmit={f.handleSubmit((v) => rec.mutate({ body: { ...v, ...(v.bankReference ? {} : { bankReference: undefined }) } }, { onSuccess: () => f.reset({ currency: 'AED', receivedOn: today() }) } as any))}>
      <EntityPicker label="Legal entity" {...f.register('legalEntityId', { required: true })} /><PartyPicker role="customer" label="Customer" {...f.register('partyId', { required: true })} /><FormGrid cols={3}><TextField label="Amount" inputMode="decimal" {...f.register('amount', { required: true })} /><TextField label="Currency" maxLength={3} {...f.register('currency')} /><TextField label="Date" type="date" {...f.register('receivedOn', { required: true })} /></FormGrid><TextField label="Bank reference" {...f.register('bankReference')} /><Button type="submit" disabled={rec.isPending}>Record receipt</Button><ErrorNote e={rec.error} /></form></Card>
      <Card title="Allocate to invoice"><form className="grid gap-3" onSubmit={g.handleSubmit((v) => alloc.mutate({ params: { id: v.paymentId }, body: { invoiceId: v.invoiceId, amount: v.amount, allocationKey: crypto.randomUUID() } }, { onSuccess: () => g.reset() } as any))}>
        <SelectField label="Receipt" {...g.register('paymentId', { required: true })}><option value="">Select…</option>{withRoom.map((p) => <option key={p.id} value={p.id}>{p.party} · {money(p.available, p.currency)} free</option>)}</SelectField>
        <SelectField label="Invoice" {...g.register('invoiceId', { required: true })}><option value="">Select…</option>{open.map((i) => <option key={i.id} value={i.id}>{i.ref} · {money(Number(i.total) - Number(i.amount_allocated), i.currency)} open</option>)}</SelectField>
        <TextField label="Amount" inputMode="decimal" {...g.register('amount', { required: true })} /><Button type="submit" variant="ghost" disabled={alloc.isPending}>Allocate</Button><ErrorNote e={alloc.error} /><p className="text-xs text-steel">Refused if it exceeds the receipt balance or the invoice balance, or the currencies differ.</p></form></Card></div></div>);
}
function Bills() {
  const q = useOp('listSupplierBills'); const rec = useCmd('recordSupplierBill', { invalidate: ['listSupplierBills', 'listCharges'] }); const f = useForm<any>({ defaultValues: { currency: 'AED' } });
  const columns = useMemo(() => [bc.accessor('supplier_invoice_no', { header: 'Supplier invoice', cell: (c) => <Mono>{c.getValue()}</Mono> }), bc.accessor('supplier', { header: 'Supplier' }), bc.accessor('job_ref', { header: 'Job' }), bc.accessor('amount', { header: 'Amount', cell: (c) => money(c.getValue(), c.row.original.currency) }),
    bc.accessor('variance', { header: 'Variance vs accrual', cell: (c) => Number(c.getValue()) === 0 ? <Chip tone="ok">matches</Chip> : <Chip tone="hold">{money(c.getValue(), c.row.original.currency)}</Chip> }), bc.accessor('status', { header: 'Status', cell: (c) => <StatusChip s={c.getValue()} /> })], []);
  return (<div className="grid grid-cols-1 lg:grid-cols-[1fr_340px] items-start gap-5"><Card title="Supplier bills"><DataTable q={q} columns={columns} empty="No supplier bills recorded." label="Filter bills" /></Card>
    <Card title="Record supplier bill"><form className="grid gap-3" onSubmit={f.handleSubmit((v) => rec.mutate({ body: v }, { onSuccess: () => f.reset({ currency: 'AED' }) } as any))}><EntityPicker label="Legal entity" {...f.register('legalEntityId', { required: true })} /><PartyPicker label="Supplier" {...f.register('supplierPartyId', { required: true })} /><JobPicker label="Job" {...f.register('jobId', { required: true })} />
      <TextField label="Supplier invoice no." {...f.register('supplierInvoiceNo', { required: true })} /><FormGrid><TextField label="Amount" inputMode="decimal" {...f.register('amount', { required: true })} /><TextField label="Currency" maxLength={3} {...f.register('currency')} /></FormGrid><Button type="submit" disabled={rec.isPending}>Record bill</Button><ErrorNote e={rec.error} /><p className="text-xs text-steel">Duplicate supplier invoice numbers are refused; the accrual is cleared and any variance shown.</p></form></Card></div>);
}
function Charges() {
  const q = useOp('listCharges'); const create = useCmd('createCharge', { invalidate: ['listCharges'] }); const f = useForm<any>({ defaultValues: { kind: 'revenue', currency: 'AED', quantity: '1', taxCode: 'SR5' } });
  const columns = useMemo(() => [cc.accessor('description', { header: 'Charge', cell: (c) => <b className="font-display">{c.getValue()}</b> }), cc.accessor('kind', { header: 'Type', cell: (c) => <Chip tone={c.getValue() === 'revenue' ? 'ok' : 'idle'}>{c.getValue()}</Chip> }), cc.accessor('party', { header: 'Party', cell: (c) => c.getValue() ?? '—' }), cc.accessor('amount', { header: 'Amount', cell: (c) => money(c.getValue(), c.row.original.currency) }), cc.accessor('tax_code', { header: 'Tax' }), cc.accessor('status', { header: 'Status', cell: (c) => <StatusChip s={c.getValue()} /> })], []);
  return (<div className="grid grid-cols-1 lg:grid-cols-[1fr_340px] items-start gap-5"><Card title="Charges (revenue and cost)"><DataTable q={q} columns={columns} empty="No charges yet." label="Filter charges" /></Card>
    <Card title="Add charge"><form className="grid gap-3" onSubmit={f.handleSubmit((v) => create.mutate({ body: { ...v, sourceEventKey: `manual:${crypto.randomUUID()}`, ...(v.partyId ? {} : { partyId: undefined }) } as any }, { onSuccess: () => f.reset({ kind: 'revenue', currency: 'AED', quantity: '1', taxCode: 'SR5' }) } as any))}>
      <JobPicker label="Job" {...f.register('jobId', { required: true })} /><FormGrid><SelectField label="Type" {...f.register('kind')}><option value="revenue">revenue</option><option value="cost">cost</option></SelectField><SelectField label="Tax" {...f.register('taxCode')}>{['SR5', 'ZR', 'EX', 'OOS'].map((t) => <option key={t}>{t}</option>)}</SelectField></FormGrid>
      <TextField label="Description" {...f.register('description', { required: true })} /><FormGrid cols={3}><TextField label="Qty" inputMode="decimal" {...f.register('quantity')} /><TextField label="Unit amount" inputMode="decimal" {...f.register('unitAmount', { required: true })} /><TextField label="Currency" maxLength={3} {...f.register('currency')} /></FormGrid>
      <PartyPicker label="Counter-party (cost)" {...f.register('partyId')} /><Button type="submit" disabled={create.isPending}>Add charge</Button><ErrorNote e={create.error} /></form></Card></div>);
}
export default function Finance() {
  return (<><PageTitle title="Money" sub="Billing → ledger → e-invoice are separate states"><Link href="/intelligence" className="text-sm underline">Receivables ageing &amp; profitability →</Link></PageTitle>
    <SectionTabs sections={[{ id: 'invoices', label: 'Invoices', content: <Invoices /> }, { id: 'payments', label: 'Receipts', content: <Payments /> }, { id: 'bills', label: 'Supplier bills', content: <Bills /> }, { id: 'charges', label: 'Charges', content: <Charges /> }]} /></>);
}
