import { D } from '@dbl/contracts';
import { BrandedDoc, C, fmt, fmtDate, fmtDateTime, type Issuer, type Party } from './layout';

const taxRate = (r: string | number) => `${D(r).mul(100).toDecimalPlaces(2).toString()}%`;
const partyLines = (p: Party) => [p.name, p.address, p.trn ? `TRN ${p.trn}` : null, [p.email, p.phone].filter(Boolean).join(' · ') || null];

export interface InvoiceData {
  issuer: Issuer; customer: Party; number: string | null; status: 'draft' | 'approved' | 'posted' | 'credited'; issueDate?: string | null; dueDate?: string | null; currency: string; jobRef: string; einvoiceStatus?: string | null;
  lines: Array<{ description: string; net: string; taxCode: string; taxRate: string | number; tax: string }>; subtotal: string; taxTotal: string; total: string; paid: string; balance: string; generatedAt?: Date;
}
/** UAE-style tax invoice: supplier and customer identity with TRNs, sequential number, date of supply, per-line net/VAT, VAT summary by rate, totals in invoice currency. */
export function renderInvoice(i: InvoiceData): Promise<Buffer> {
  const posted = i.status === 'posted' || i.status === 'credited';
  const b = new BrandedDoc({ type: posted ? (i.status === 'credited' ? 'Credited tax invoice' : 'Tax invoice') : 'Draft invoice', number: i.number ?? 'DRAFT — number allocated at posting', issuer: i.issuer, subtitle: `Job ${i.jobRef}`, watermark: posted ? undefined : 'DRAFT', generatedAt: i.generatedAt });
  const d = b.doc; const y0 = d.y; const half = (b.width - 24) * 0.5;
  const yL = b.block('Supplier', partyLines(i.issuer), b.left, y0, half); const yR = b.block('Bill to', partyLines(i.customer), b.left + half + 24, y0, half); d.y = Math.max(yL, yR) + 8;
  d.y = b.facts([['Invoice no.', i.number ?? 'DRAFT'], ['Invoice date', i.issueDate ? fmtDate(i.issueDate) : null], ['Due date', i.dueDate ? fmtDate(i.dueDate) : null], ['Currency', i.currency], ['Job reference', i.jobRef], ['E-invoice', i.einvoiceStatus && i.einvoiceStatus !== 'not_required' ? i.einvoiceStatus.replace('_', ' ') : null]], b.left, d.y, b.width) + 6;
  b.heading('Services');
  b.table([{ key: 'n', header: '#', width: 22 }, { key: 'description', header: 'Description', width: 230 }, { key: 'net', header: `Net (${i.currency})`, width: 78, align: 'right', mono: true }, { key: 'rate', header: 'VAT', width: 48, align: 'right', mono: true }, { key: 'tax', header: `VAT (${i.currency})`, width: 74, align: 'right', mono: true }, { key: 'gross', header: `Total (${i.currency})`, width: 82, align: 'right', mono: true }],
    i.lines.map((l, k) => ({ n: String(k + 1), description: l.description, net: fmt(l.net), rate: `${l.taxCode} ${taxRate(l.taxRate)}`, tax: fmt(l.tax), gross: fmt(D(l.net).plus(l.tax).toString()) })));
  const byRate = new Map<string, { net: ReturnType<typeof D>; tax: ReturnType<typeof D> }>(); for (const l of i.lines) { const k = `${l.taxCode} ${taxRate(l.taxRate)}`; const c = byRate.get(k) ?? { net: D(0), tax: D(0) }; byRate.set(k, { net: c.net.plus(l.net), tax: c.tax.plus(l.tax) }); }
  const rows: Array<[string, string]> = [['Subtotal', `${i.currency} ${fmt(i.subtotal)}`]]; for (const [k, v] of byRate) rows.push([`VAT ${k}`, `${i.currency} ${fmt(v.tax.toString())}`]); rows.push(['Total VAT', `${i.currency} ${fmt(i.taxTotal)}`], ['Invoice total', `${i.currency} ${fmt(i.total)}`]);
  if (posted) rows.push(['Paid to date', `${i.currency} ${fmt(i.paid)}`], ['Balance due', `${i.currency} ${fmt(i.balance)}`]);
  b.totals(rows);
  const bank = i.issuer.bank; if (posted && bank && (bank.iban || bank.bankName)) { b.heading('Payment instructions'); d.y = b.facts([['Bank', bank.bankName], ['Account name', bank.accountName ?? i.issuer.name], ['IBAN', bank.iban], ['SWIFT', bank.swift], ['Payment reference', i.number]], b.left, d.y, b.width * 0.62) + 4; }
  b.heading('Terms'); b.paragraph(`Payment is due by ${i.dueDate ? fmtDate(i.dueDate) : 'the due date shown'} in ${i.currency}. Please quote the invoice number with your payment. All services are subject to the company's standard trading terms and applicable law. Amounts are shown to two decimals; VAT is calculated per line and rounded half-up.${posted ? '' : ' THIS IS A DRAFT FOR REVIEW AND IS NOT A TAX INVOICE.'} This document is generated by the system and is valid without signature.`);
  return b.finish();
}

export interface QuoteData { issuer: Issuer; customer: Party; number: string; revision: number; status: string; currency: string; validUntil: string; mode: string; origin: string; destination: string; incoterm?: string | null;
  lines: Array<{ description: string; chargeType: string; quantity: string; unit?: string | null; unitPrice: string; taxCode: string; taxRate: string | number }>; totals: { net: string; tax: string; total: string }; generatedAt?: Date }
export function renderQuotation(q: QuoteData): Promise<Buffer> {
  const final = ['approved', 'sent', 'accepted'].includes(q.status);
  const b = new BrandedDoc({ type: 'Quotation', number: `${q.number}${q.revision > 1 ? ` · revision ${q.revision}` : ''}`, issuer: q.issuer, subtitle: `Valid until ${fmtDate(q.validUntil)}`, watermark: final ? undefined : 'DRAFT', generatedAt: q.generatedAt });
  const d = b.doc; const y0 = d.y; const half = (b.width - 24) * 0.5;
  const yL = b.block('Prepared for', partyLines(q.customer), b.left, y0, half); const yR = b.block('Prepared by', partyLines(q.issuer), b.left + half + 24, y0, half); d.y = Math.max(yL, yR) + 8;
  d.y = b.facts([['Quotation no.', q.number], ['Revision', String(q.revision)], ['Valid until', fmtDate(q.validUntil)], ['Mode', q.mode.replace('_', ' ')], ['Route', `${q.origin} to ${q.destination}`], ['Incoterm', q.incoterm], ['Currency', q.currency]], b.left, d.y, b.width) + 4;
  b.heading('Charges');
  b.table([{ key: 'n', header: '#', width: 22 }, { key: 'description', header: 'Description', width: 214 }, { key: 'qty', header: 'Qty', width: 52, align: 'right', mono: true }, { key: 'unit', header: `Unit price (${q.currency})`, width: 90, align: 'right', mono: true }, { key: 'net', header: `Net (${q.currency})`, width: 80, align: 'right', mono: true }, { key: 'rate', header: 'VAT', width: 56, align: 'right', mono: true }],
    q.lines.map((l, k) => ({ n: String(k + 1), description: `${l.description}${l.chargeType !== 'fixed' ? `  (${l.chargeType.replace('_', ' ')})` : ''}`, qty: `${D(l.quantity).toString()}${l.unit ? ' ' + l.unit : ''}`, unit: fmt(l.unitPrice), net: fmt(D(l.quantity).mul(l.unitPrice).toString()), rate: `${l.taxCode} ${taxRate(l.taxRate)}` })));
  b.totals([['Net total', `${q.currency} ${fmt(q.totals.net)}`], ['VAT', `${q.currency} ${fmt(q.totals.tax)}`], ['Quotation total', `${q.currency} ${fmt(q.totals.total)}`]]);
  b.heading('Conditions'); b.paragraph('Prices are valid until the date shown and are based on the cargo details and route above. Charges marked estimated or at cost are invoiced at actual cost. Rates exclude duties, customs fees, demurrage, detention and storage unless listed. Transit times are estimates and not guaranteed. Services are subject to the company\'s standard trading terms.');
  if (final) { b.ensure(70); d.moveDown(1); b.label('Acceptance', b.left, d.y); const y = d.y + 14; d.rect(b.left, y, b.width, 46).strokeColor(C.line).lineWidth(0.8).stroke(); d.font('Body').fontSize(8.5).fillColor(C.steel).text('Accepted for and on behalf of the customer — name, signature, date:', b.left + 8, y + 6, { width: b.width - 16 }); d.y = y + 52; }
  return b.finish();
}

export interface ShipmentReportData { issuer: Issuer; customer?: Party | null; ref: string; jobRef?: string | null; mode: string; status: string; origin: string; destination: string; incoterm?: string | null; deliveredAt?: string | null; currentMilestone?: string | null;
  legs: Array<{ seq: number; mode: string; origin: string; destination: string; operator?: string | null; plannedArrival?: string | null; estimatedArrival?: string | null; actualArrival?: string | null }>;
  cargo: Array<{ description: string; quantity: string; kind: string; grossWeightKg?: string | null; hsCode?: string | null }>;
  events: Array<{ code: string; time: string; source: string; actual: boolean }>; generatedAt?: Date }
export function renderShipmentReport(s: ShipmentReportData): Promise<Buffer> {
  const b = new BrandedDoc({ type: 'Shipment status report', number: s.ref, issuer: s.issuer, subtitle: s.jobRef ? `Job ${s.jobRef}` : undefined, generatedAt: s.generatedAt });
  const d = b.doc; const y0 = d.y; const half = (b.width - 24) * 0.5;
  const yL = s.customer ? b.block('Customer', partyLines(s.customer), b.left, y0, half) : y0; const yR = b.block('Movement', [`${s.origin} to ${s.destination}`, `${s.mode.replace('_', ' ')}${s.incoterm ? ` · ${s.incoterm}` : ''}`], b.left + half + 24, y0, half); d.y = Math.max(yL, yR) + 8;
  d.y = b.facts([['Shipment', s.ref], ['Status', s.status.replace('_', ' ')], ['Current milestone', s.currentMilestone?.replace(/_/g, ' ')], ['Delivered', s.deliveredAt ? fmtDate(s.deliveredAt) : null]], b.left, d.y, b.width) + 4;
  if (s.legs.length) { b.heading('Route'); b.table([{ key: 'seq', header: '#', width: 22 }, { key: 'mode', header: 'Mode', width: 64 }, { key: 'route', header: 'Route', width: 150 }, { key: 'op', header: 'Operator', width: 100 }, { key: 'plan', header: 'Planned', width: 64 }, { key: 'eta', header: 'Estimated', width: 64 }, { key: 'act', header: 'Arrived', width: 64 }],
    s.legs.map((l) => ({ seq: String(l.seq), mode: l.mode.replace('_', ' '), route: `${l.origin} to ${l.destination}`, op: l.operator ?? '—', plan: fmtDate(l.plannedArrival), eta: fmtDate(l.estimatedArrival), act: fmtDate(l.actualArrival) }))); }
  if (s.cargo.length) { b.heading('Cargo'); b.table([{ key: 'description', header: 'Description', width: 230 }, { key: 'qty', header: 'Quantity', width: 90, align: 'right', mono: true }, { key: 'kg', header: 'Gross weight', width: 90, align: 'right', mono: true }, { key: 'hs', header: 'HS code', width: 80, mono: true }],
    s.cargo.map((c) => ({ description: c.description, qty: `${D(c.quantity).toString()} ${c.kind}`, kg: c.grossWeightKg ? `${fmt(c.grossWeightKg)} kg` : '—', hs: c.hsCode ?? '—' }))); }
  b.heading('Tracking history'); b.table([{ key: 'time', header: 'Date / time', width: 120, mono: true }, { key: 'code', header: 'Milestone', width: 200 }, { key: 'src', header: 'Source', width: 90 }, { key: 'kind', header: 'Kind', width: 70 }],
    s.events.length ? s.events.map((e) => ({ time: fmtDateTime(e.time), code: e.code.replace(/_/g, ' '), src: e.source, kind: e.actual ? 'Actual' : 'Estimate' })) : [{ time: '—', code: 'No tracking updates recorded yet', src: '', kind: '' }]);
  b.paragraph('Estimates are indicative and may change; actuals are reported by the carrier, our partners or our own staff, and are shown with their source.');
  return b.finish();
}
