import {beforeAll,afterAll,it,expect} from 'vitest';
import {world,close,makeParty,approvedDocument,type World,type Client} from './helpers';
import {randomUUID} from 'node:crypto';
let w:World,author:Client,reader:Client,reviewer:Client,owner:string;
const article=()=>({legalEntityId:w.a.legalEntityId,branchId:null,key:'cargo_sop',title:'Cargo handling SOP',category:'sop',content:'Verify cargo identity, source documents and handling instructions.',changeNote:'Initial controlled procedure for cargo handling'});
const future=()=>new Date(Date.now()+86400000*30).toISOString().slice(0,10);
beforeAll(async()=>{w=await world();author=await w.member(w.a.tenantId,'governance-author',['freight_ops']);reader=await w.member(w.a.tenantId,'knowledge-reader',['sales']);reviewer=await w.member(w.a.tenantId,'risk-reviewer',['quality_manager']);owner=(await author.get('/me')).body.membershipId;});afterAll(async()=>close(w));
it('publishes independently reviewed immutable knowledge and acknowledges each content hash separately',async()=>{
 const a=await author.cmd('/knowledge',article());expect(a.status).toBe(201);expect(a.body.content_sha256).toMatch(/^[a-f0-9]{64}$/);expect((await reader.get('/knowledge')).body).toHaveLength(0);expect((await reader.cmd(`/knowledge/${a.body.id}/acknowledge`)).status).toBe(409);expect((await author.cmd(`/knowledge/${a.body.id}/publish`,{reviewNote:'Checked the SOP source and safety requirements'})).status).toBe(403);
 const self=await w.owner.cmd('/knowledge',{...article(),key:'own_policy'});expect((await w.owner.cmd(`/knowledge/${self.body.id}/publish`,{reviewNote:'Checked the SOP source and safety requirements'})).body.code).toBe('SEPARATION_OF_DUTIES');
 expect((await w.owner.cmd(`/knowledge/${a.body.id}/publish`,{reviewNote:'Checked the SOP source and safety requirements'})).status).toBe(200);const key=randomUUID();const ack=await reader.cmd(`/knowledge/${a.body.id}/acknowledge`,{},key);expect(ack.status).toBe(200);expect((await reader.cmd(`/knowledge/${a.body.id}/acknowledge`,{},key)).body).toEqual(ack.body);await expect(w.su.query(`UPDATE collab.knowledge_revisions SET content='tampered' WHERE id=$1`,[a.body.id])).rejects.toThrow(/immutable/);
 const b=await author.cmd('/knowledge',{...article(),content:'Verify cargo identity and photograph seals before cargo handling.'});expect(b.body.revision).toBe(2);expect(b.body.content_sha256).not.toBe(a.body.content_sha256);await w.owner.cmd(`/knowledge/${b.body.id}/publish`,{reviewNote:'Reviewed revised seal photography requirement'});const rows=(await reader.get('/knowledge?search=seals')).body;expect(rows).toHaveLength(1);expect(rows[0].acknowledged).toBe(false);
});
it('scores risks, retains independent review history and requires approved evidence for closure',async()=>{
 const body={legalEntityId:w.a.legalEntityId,branchId:null,title:'Carrier document mismatch',category:'operational',description:'Incorrect shipping document can delay clearance and custody release.',likelihood:4,impact:5,mitigation:'Verify source documents and have a second reviewer approve corrections.',ownerMembershipId:owner,nextReviewOn:future()};const r=await author.cmd('/risks',body);expect(r.status).toBe(201);expect(r.body.inherent_score).toBe(20);
 const review={outcome:'mitigating',residualLikelihood:2,residualImpact:3,reviewNote:'Independent review confirms controls reduced the exposure',mitigation:'Continue second review and match all source documents before release.',nextReviewOn:future(),evidenceDocumentId:null};expect((await w.owner.cmd(`/risks/${r.body.id}/reviews`,review,randomUUID(),{'If-Match':'99'})).body.code).toBe('VERSION_CONFLICT');const a=await reviewer.cmd(`/risks/${r.body.id}/reviews`,review,randomUUID(),{'If-Match':'1'});expect(a.status).toBe(200);expect(a.body.residual_score).toBe(6);
 expect((await reviewer.cmd(`/risks/${r.body.id}/reviews`,{...review,outcome:'closed'})).status).toBe(422);expect((await reviewer.cmd(`/risks/${r.body.id}/reviews`,{...review,outcome:'closed',evidenceDocumentId:randomUUID()})).body.code).toBe('DOCUMENT_NOT_CLEAN');const doc=await approvedDocument(w,w.owner,{docType:'risk_review',issuerKind:'internal',relatedType:'risk',relatedId:r.body.id});expect((await reviewer.cmd(`/risks/${r.body.id}/reviews`,{...review,outcome:'closed',evidenceDocumentId:doc},randomUUID(),{'If-Match':String(a.body.version)})).status).toBe(200);const detail=(await reviewer.get(`/risks/${r.body.id}`)).body;expect(detail.reviews).toHaveLength(2);expect(detail.status).toBe('closed');await expect(w.su.query(`DELETE FROM collab.risk_reviews WHERE risk_id=$1`,[r.body.id])).rejects.toThrow(/append-only/);expect((await reviewer.cmd(`/risks/${r.body.id}/reviews`,review)).status).toBe(409);
});
it('enforces tenant and external isolation and blocks independent review by the risk owner',async()=>{
 const a=await author.cmd('/knowledge',{...article(),key:'private_draft'});const foreign=await w.member(w.b.tenantId,'foreign-governance',['owner']);expect((await foreign.cmd(`/knowledge/${a.body.id}/publish`,{reviewNote:'Unauthorized cross-tenant publication attempt'})).status).toBe(404);
 const p=await makeParty(w.owner,'Governance portal',['customer']);const portal=await w.member(w.a.tenantId,'gov-portal',['owner'],{workspace:'customer',partyId:p});expect((await portal.get('/knowledge')).status).toBe(403);expect((await portal.get('/risks')).status).toBe(403);
 const self=await w.owner.cmd('/risks',{legalEntityId:w.a.legalEntityId,branchId:null,title:'Self owned review risk',category:'security',description:'Administrative owner must not review and accept their own exposure.',likelihood:2,impact:4,mitigation:'Use an independent authorized reviewer for this exposure.',ownerMembershipId:(await w.owner.get('/me')).body.membershipId,nextReviewOn:future()});expect((await w.owner.cmd(`/risks/${self.body.id}/reviews`,{outcome:'mitigating',residualLikelihood:1,residualImpact:2,reviewNote:'Attempt to review and accept my own exposure',mitigation:'I cannot independently approve this mitigation.',nextReviewOn:future(),evidenceDocumentId:null})).body.code).toBe('SEPARATION_OF_DUTIES');
});
