import {expect,test,type Page} from '@playwright/test';
const tenant=process.env.TENANT_ID!;
async function login(page:Page,subject:string){await page.goto('/login');await page.waitForFunction(()=>{const m=document.querySelector('main');return !!m&&Object.keys(m).some(k=>k.startsWith('__reactProps'));});await page.getByPlaceholder('OIDC subject').fill(subject);await page.getByPlaceholder('Tenant id (uuid)').fill(tenant);await page.getByRole('button',{name:'Dev sign in'}).click();await page.waitForURL('/');}
const logout=(page:Page)=>page.goto('/api/auth/logout');
test('business calendar work can pause, resume and transfer only through recipient acknowledgement',async({page})=>{
 test.setTimeout(180000);const tag=Date.now(),title=`Browser work ${tag}`;await login(page,'layla');await page.getByRole('link',{name:'Work control',exact:true}).click();await page.getByRole('tab',{name:'SLA calendars',exact:true}).click();
 await page.getByLabel('Calendar key',{exact:true}).fill(`browser_${tag}`);await page.getByLabel('Calendar name',{exact:true}).fill(`Browser calendar ${tag}`);await page.getByRole('button',{name:'Publish calendar',exact:true}).click();await expect(page.getByText(`Browser calendar ${tag} · v1`,{exact:true})).toBeVisible();
 await page.getByRole('tab',{name:'Work queue',exact:true}).click();await page.getByLabel('Legal entity',{exact:true}).selectOption({index:1});await page.getByLabel('Work title',{exact:true}).fill(title);await page.getByLabel('Required outcome and evidence',{exact:true}).fill('Review source documents and confirm correct cargo identification.');await page.getByLabel('Department',{exact:true}).fill('Documentation');await page.getByLabel('Assignee',{exact:true}).selectOption({label:'layla'});await page.getByLabel('SLA calendar',{exact:true}).selectOption({label:`Browser calendar ${tag} · v1`});await page.getByRole('button',{name:'Create work item',exact:true}).click();await expect(page.getByRole('button',{name:title,exact:true})).toBeVisible();
 await page.getByLabel('Action note',{exact:true}).fill('Started review of source documents');await page.getByRole('button',{name:'Start work',exact:true}).click();await expect(page.getByRole('button',{name:'Pause work',exact:true})).toBeVisible();await page.getByLabel('Action note',{exact:true}).fill('Waiting for the missing source documents');await page.getByRole('button',{name:'Pause work',exact:true}).click();await expect(page.getByRole('button',{name:'Resume work',exact:true})).toBeVisible();await page.getByLabel('Action note',{exact:true}).fill('Source documents received; resume review');await page.getByRole('button',{name:'Resume work',exact:true}).click();await expect(page.getByRole('button',{name:'Complete work',exact:true})).toBeVisible();
 await page.getByRole('tab',{name:'Shift handover',exact:true}).click();await page.getByLabel('Receiving colleague',{exact:true}).selectOption({label:'rami'});await page.getByLabel('Outstanding work to hand over',{exact:true}).selectOption({label:`${title} · in_progress`});const note=`Handover ${tag}: review the remaining source evidence`;await page.getByLabel('Handover instructions and critical issues',{exact:true}).fill(note);await page.getByRole('button',{name:'Prepare handover',exact:true}).click();await expect(page.getByText(note,{exact:true})).toBeVisible();
 await logout(page);await login(page,'rami');await page.goto('/work');await page.getByRole('tab',{name:'Shift handover',exact:true}).click();await expect(page.getByText(note,{exact:true})).toBeVisible();const handover=page.locator('section').filter({has:page.getByText(note,{exact:true})});await handover.getByLabel('Acknowledgement note',{exact:true}).fill('I accept responsibility and will complete the source review');await handover.getByRole('button',{name:'Acknowledge and take responsibility',exact:true}).click();await expect(handover.getByText('acknowledged',{exact:true})).toBeVisible();await page.getByRole('tab',{name:'Work queue',exact:true}).click();await page.getByRole('button',{name:title,exact:true}).click();await page.getByLabel('Action note',{exact:true}).fill('Review completed; source evidence was verified');await page.getByRole('button',{name:'Complete work',exact:true}).click();await expect(page.getByRole('button',{name:'Complete work',exact:true})).toHaveCount(0);
});
test('a knowledge author creates a revision and an independent reviewer publishes it before acknowledgement',async({page})=>{
 test.setTimeout(180000);const tag=Date.now(),title=`Browser SOP ${tag}`;await login(page,'rami');await page.goto('/governance');await page.getByLabel('Legal entity',{exact:true}).selectOption({index:1});await page.getByLabel('Article key',{exact:true}).fill(`sop_${tag}`);await page.getByLabel('Article title',{exact:true}).fill(title);await page.getByLabel('Article content',{exact:true}).fill('Verify package identity and the source paperwork before custody release.');await page.getByLabel('Revision change note',{exact:true}).fill('Initial controlled version for browser acceptance');await page.getByRole('button',{name:'Create article draft',exact:true}).click();await expect(page.getByRole('button',{name:`${title} · revision 1`,exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Publish reviewed revision'})).toHaveCount(0);
 await logout(page);await login(page,'layla');await page.goto('/governance');await page.getByRole('button',{name:`${title} · revision 1`,exact:true}).click();await page.getByLabel('Independent publication review',{exact:true}).fill('Reviewed the cargo identity controls and source requirements');await page.getByRole('button',{name:'Publish reviewed revision',exact:true}).click();await expect(page.getByRole('button',{name:'I have read this revision',exact:true})).toBeVisible();await page.getByRole('button',{name:'I have read this revision',exact:true}).click();await expect(page.getByRole('button',{name:'Revision acknowledged',exact:true})).toBeDisabled();
});
test('an owner can revoke a newly provisioned user session and the browser identity endpoint clears access',async({page,browser})=>{
 test.setTimeout(180000);const subject=`browser_user_${Date.now()}`;await login(page,'layla');await page.goto('/admin');await page.getByLabel('Login subject',{exact:true}).fill(subject);await page.getByLabel('Role template').selectOption({label:'Sales'});await page.getByRole('button',{name:'Add member',exact:true}).click();await expect(page.getByText(subject,{exact:true}).first()).toBeVisible();
 const user=await browser.newPage({baseURL:'http://localhost:3000'});try{await login(user,subject);expect((await user.request.get('/api/auth/me')).status()).toBe(200);await page.getByRole('tab',{name:'Access control',exact:true}).click();await page.getByLabel('Membership to manage',{exact:true}).selectOption({label:`${subject} · staff · active`});await page.getByLabel('Access change reason',{exact:true}).fill('Lost device; invalidate previously issued access tokens');await page.getByRole('button',{name:'Revoke existing sessions',exact:true}).click();await expect(page.getByText('Access change recorded.',{exact:true})).toBeVisible();expect((await user.request.get('/api/auth/me')).status()).toBe(401);}finally{await user.close();}
});
test('accountant requests an ended period close and an independent finance manager approves it',async({page})=>{
 test.setTimeout(180000);await login(page,'sana');await page.goto('/finance');await page.getByRole('tab',{name:'Accounting periods',exact:true}).click();
 const now=new Date(),lastEnd=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),0)),start=new Date(Date.UTC(lastEnd.getUTCFullYear(),lastEnd.getUTCMonth(),1)),label=`${start.toISOString().slice(0,10)} → ${lastEnd.toISOString().slice(0,10)}`;await page.getByRole('button',{name:label,exact:true}).first().click();
 await page.getByLabel('Period change reason and reconciliation evidence',{exact:true}).fill('Prior month ledger reviewed and reconciled for controlled period close');await page.getByRole('button',{name:'Request reviewed period change',exact:true}).click();await expect(page.getByText('pending',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Approve period change',exact:true})).toHaveCount(0);
 await logout(page);await login(page,'faisal');await page.goto('/finance');await page.getByRole('tab',{name:'Accounting periods',exact:true}).click();await page.getByRole('button',{name:label,exact:true}).first().click();await page.getByLabel('Independent period review note',{exact:true}).fill('Independently reviewed the period movement and reconciliation snapshot');await page.getByRole('button',{name:'Approve period change',exact:true}).click();await expect(page.getByText('approved',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Approve period change',exact:true})).toHaveCount(0);
});
